### ISSUE TITLE
Issue in creation of 3D tiles for underground utilities

### ISSUE THREAD

**Issue by shreya-bobde** [Gaia3D/mago-3d-tiler#12]
Currently working on Underground Utilities for creation of 3D pipes. For that shapefile, height and diameter attribute is required. Your tool has height attribute but not diameter attribute. What would be the possible solution for this?

**Comment by znkim** [comment]
Unfortunately, we don't have the feature to create 3D pipes, so we don't have a diameter option. 
But the feature seems like a great idea, and we'll consider developing that feature as well.
