### ISSUE TITLE
meaning of the parameters of LOD

### ISSUE THREAD

**Issue by nakijun** [Gaia3D/mago-3d-tiler#19]
Hello, 

i saw the lines bellow in LevelOfDetial.java

public enum LevelOfDetail {
    NONE(-1,0, 0, 1.0f, new float[]{1.0f, 1.0f, 1.0f}),
    LOD0(0,0,0, 1.0f, new float[]{1.0f, 0.4f, 0.4f}),
    LOD1(1, 2, 8, 0.5f, new float[]{0.4f, 1.0f, 0.4f}),
    LOD2(2, 4, 50, 0.25f, new float[]{0.4f, 0.4f, 1.0f}),
    LOD3(3, 8, 120, 0.125f, new float[]{1.0f, 1.0f, 0.4f}),
    LOD4(4, 16, 180, 0.0625f, new float[]{0.4f, 1.0f, 1.0f}),
    LOD5(5, 32, 240, 0.03125f, new float[]{1.0f, 0.4f, 1.0f}),
    LOD6(6, 64, 300, 0.01625f, new float[]{1.0f, 1.0f, 1.0f});

for example, LOD6(6, 64, 300, 0.01625f, new float[]{1.0f, 1.0f, 1.0f}) 
would you tell me about the meaning of each parameter?
and more, if I add the value above LOD6 , is it meaningful doing?

thank you.

**Comment by znkim** [comment]
Hi @nakijun

Enumeration refers to the level of detail of a 3D model.
Level 0 is the most detailed and the higher levels are simpler.
The Geometric Error in a Level affects whether or not the model is visible from the camera's perspective in the scene.

We are specifying GeometricError based on the size of the original model, so dividing by more than LOD4 is not particularly meaningful in most situations.

The code below is a constant that is matched with each parameter.
```
    final int level;
    final int geometricError;
    final int geometricErrorBlock;
    final float textureScale;
    final float[] debugColor;
```

level : means the LOD level
geometricError : maximum value of GeomtricError for filtering 3d models in tiles
geometricErrorBlock : a more loosely applied GeometricError filter value
textureScale : Texture scale of 3D data based on LOD
debugColor : High-contrast debugging color for testing models generated based on LOD

Thank you.
