### ISSUE TITLE
can support draco or ktx2 image compressions in b3dm files?

### ISSUE THREAD

**Issue by nakijun** [Gaia3D/mago-3d-tiler#20]
Hello, znkim

i heard that when creating 3D tiling, the draco or ktx2 compression algorithm can reduce the file size and network loading.
so, i tested it with another 3D tiling creation program with ktx2 + draco compression options, the result of the file size was reduced by 3/1.

is there a process for texture image compressions while creating a 3d tileing b3dm files in mago-3d-tiler?
If do compressing images in Mago-3D-tiler, what method are using? 
If there is no compression function currently, do you plan to support this function in the future?

thank you.

**Comment by znkim** [comment]
Hello, @nakijun 

mago-3d-tiler does not support draco and KTX compression yet. 
but we are interested in supporting draco and KTX as well. 

 currently, the mago-3d-tiler library uses JglTF as the core library to write glTF files.
unfortunately, JglTF does not support draco and KTX yet. 
See link : [JglTF, Draco compression](https://github.com/javagl/JglTF/issues/81)

So we have to either develop our own, or wait for a Java version of the Draco library to replace it.
 Developing a Java library according to the Draco specification is also a time-consuming task, so I can't say that it is possible right away.
 
 We're also exploring other ways to lighten data.

Thank you.
