### ISSUE TITLE
newly added largeMesh option not working

### ISSUE THREAD

**Issue by nakijun** [Gaia3D/mago-3d-tiler#21]
Hello

i ran windows jar file with bellow options. 
it worked correctly and showed to cesiumjs nicely.

--input C:\data\3ds --output C:\data\3ds_output --inputType 3ds --crs 5186
----------------------------------------
End Process Time : 6s 192ms
Total tile contents count : 19
Total 'tileset.json' File Size : 3KB
----------------------------------------

with new added largemesh option add, ran jar with bellow options, 
--input C:\data\3ds --output C:\data\3ds_output --inputType 3ds --crs 5186 -lm true  

log like this, 

[Post] Start the post-processing.
[Post][1/24] post-process in progress. : RC0000
[Post][3/24] post-process in progress. : RC10
[Post][2/24] post-process in progress. : RC1
[Post][6/24] post-process in progress. : RC1001
[Post][5/24] post-process in progress. : RC101
...
Position buffer is null
Position buffer is null
Position buffer is null
Position buffer is null
Position buffer is null
...
Batched Set is empty
BatchedSet is null, return null.
[Post][9/24] post-process in progress. : RC1011
[Create][data] Created output data directory:
[Create][data] Created output data lod directory:
[Post][10/24] post-process in progress. : RC11
[Post][11/24] post-process in progress. : RC110
...
[Post] End the post-processing.
----------------------------------------
End Process Time : 11s 757ms
Total tile contents count : 24
Total 'tileset.json' File Size : 5KB
----------------------------------------

and it dodn't show anything on cesiumjs. 

i think largeMesh option is suitable for large area, such as city area. 
would you explain largeMesh option and how can i use correctly? 

thanks in advance.

**Comment by znkim** [comment]
First, thank you for trying out this new feature. 

This feature is for converting large mesh data into 3DTiles by segmenting it. 
This is an experimental feature that hasn't been fully tested and stabilized yet. 
It was our mistake to include it in the source.

I'll comment again when this feature is more or less complete.
