### ISSUE TITLE
How to set the format of the input file las?

### ISSUE THREAD

**Issue by wenxiayili** [Gaia3D/mago-3d-tiler#23]
This is a very good library. During its use, I encountered a problem.If you have time, please help answer this, thank you.

My command: 
` >java -jar mago-3d-tiler-1.7.0-natives-windows.jar -it las -i D:\document\cesiumlab\las\Combine.las -o D:\tranform-tool\out-put-dy -c 4547 `

But the output coordinates seem to be incorrect. The image below shows how it's displayed in Cesium.
![image](https://github.com/user-attachments/assets/df8cd98b-ee82-4ddf-b862-13790abeb5bf)

I want to output in EPSG 4978 format. How do I do this?

**Comment by znkim** [comment]
Hello @wenxiayili

First of all, thank you for using mago 3DTiler.

It looks like you want to output EPSG:4547 data as EPSG:4978 tiles.

Unfortunately, outputting to EPSG:4978 is not supported. 
According to the 3D tiles specification, The global coordinate system should use EPSG:4326.

**Comment by wenxiayili** [comment]
> Hello @wenxiayili
> 
> First of all, thank you for using mago 3DTiler.
> 
> It looks like you want to output EPSG:4547 data as EPSG:4978 tiles.
> 
> Unfortunately, outputting to EPSG:4978 is not supported. According to the 3D tiles specification, The global coordinate system should use EPSG:4326.

Thank you for taking the time to answer my questions, I really appreciate it.

I have another question I'd like to ask. I'm working with spatial coordinates in EPSG:4547, but when I try to convert them to EPSG:4326, the values don't seem to match the expected results on the map. Could you explain why this might be happening?

**Comment by znkim** [comment]
Given that your points are vertically long, we suspect that CRS EPSG:4547 was not interpreted.

Sometimes the built-in geotools are unable to interpret EPSG code. 
In such cases, you can define your own projection argument value via the ```-proj``` option.
```
 --proj "+proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +datum=GRS80 +units=m +no_defs +type=crs"
``` 

If the code above doesn't work, I'll need to do some additional debugging.

**Comment by wenxiayili** [comment]
> 相反，您的点在垂直方向上很长，我们怀疑 CRS EPSG:4547 华丽解释。
> 
> 有时内置的地理工具无法解释 EPSG 代码。 在这种情况下，您可以通过选项定义自己的投影参数值`-proj`。
> 
> ```
>  --proj "+proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +datum=GRS80 +units=m +no_defs +type=crs"
> ```
> 
> 如果上述代码不起作用，我将需要进行一些额外的调试。

thank you!
