### ISSUE TITLE
3DTile 생성시 KTX 텍스쳐 이미지 형식..

### ISSUE THREAD

**Issue by Jeongyong-park** [Gaia3D/mago-3d-tiler#25]
3DTile 생성시 KTX 텍스쳐 이미지 형식을 사용할 수 있게 해주세요 ^^

**Comment by znkim** [comment]
안녕하세요, @Jeongyong-park 

비슷한 내용의 Issue가 있어서 기존 링크로 대체하고 close하도록 하겠습니다.
https://github.com/Gaia3D/mago-3d-tiler/issues/20#issuecomment-2241963651

감사합니다.
