### ISSUE TITLE
Understanding obj to 3D tile transformation 

### ISSUE THREAD

**Issue by a-okeefe911** [Gaia3D/mago-3d-tiler#33]
Hi,

would someone please help me understand what it is that I’m doing wrong when converting an obj to 3D tiles?

My obj file is made up of v, vn and f
For example the first line is

`
v 626769.59 233220.52 14.66
`
Which is xyz coordinates in EPSG:27700 (which I’m staging at the time of conversion)

626769.59 233220.52 14.66tiles as x,y of
`626769.59 14.66`and z of `233220.52`

so I thought that maybe the y and z coordinates needed flipped then, but no. Then `626769.59 14.66 233220.52` ALSO tiles as x,y of
`626769.59 14.66 `but z of `14.66`

can someone please tell me what I’m doing wrong on the command line?

**Comment by znkim** [comment]
hello, @a-okeefe911

I understood that what you wanted was for the
X and Y axis swap, instead of swapping the Y and Z axis.

```
(626769.59, 233220.52, 14.66) -> (233220.52, 626769.59, 14.66)
```

mago-3d-tiler only includes the features to rotate -90 and 180 degrees around the x-axis.
This does not solve the issue. 
This is because these functions are for fixing Y-UP and Z-UP axis problems.

I would recommend that you modify the original data and then convert it.

Thank you.

**Comment by a-okeefe911** [comment]
Hi @znkim 

What format would mago-3d-tiler be expecting my data to be in, in order to correctly position my OBJ?

**Comment by sdson** [comment]
Hi @a-okeefe911 ,

Can you provide us some of your *.obj file to test?

**Comment by a-okeefe911** [comment]
@sdson 
Hi, yes of course. Please find an example obj attached. Many thanks for the help
[amyok_testOBJ.zip](https://github.com/user-attachments/files/17526802/amyok_testOBJ.zip)

**Comment by sdson** [comment]
Hi @a-okeefe911 ,
![image](https://github.com/user-attachments/assets/e5cbc0fa-8995-4210-a7c8-6a8e8705e5c3)
We made the 3dtile with option "-su", and the result is like the image. is correct?

**Comment by a-okeefe911** [comment]
@sdson  Hi. So the shape is correct but location is wrong. It should be in England, UK

**Comment by sdson** [comment]
@a-okeefe911 , about the location you must introduce your crs code in the option -crs.
I used a random crs code :  -crs 5186 because i dont know the real location of the object :)

**Comment by a-okeefe911** [comment]
I have been using the correct crs which is EPSG:27700, but it’s still not in the correct position

**Comment by sdson** [comment]
@a-okeefe911 , i simply used 
String inputPath = "D:\\temp2\\";
        String outputPath = "D:\\Result_mago3dTiler\\";
        String path = "amyok_testOBJ";
        String[] args = new String[]{
                "-i", inputPath + path,
                "-it", "obj",
                "-o", outputPath + path,
                "-crs", "5186",
                "-su"
        };

**Comment by a-okeefe911** [comment]
"-su" seemed to fix my issues! Thank you so much
