### ISSUE TITLE
출력물 타일파일의 크기 및 용량

### ISSUE THREAD

**Issue by t2ols** [Gaia3D/mago-3d-tiler#4]
우선 흥미로운 프로젝트를 공개해 주셔서 감사합니다.

테스트 과정중에서 생성되는 타일의 용량이 400Mb 가까이 생성되고 있어서 실행 옵션등의 설정이 따로 있나 문의 드립니다.

source : OBJ 273Mb

실행 옵션
-aa 
-mt 
-nl 0 
-xl 6 
--crs 5186 
--inputType OBJ 

┌┬┐┌─┐┌─┐┌─┐  ┌┬┐┬┬  ┌─┐┬─┐
│││├─┤│ ┬│ │───│ ││  ├┤ ├┬┘
┴ ┴┴ ┴└─┘└─┘   ┴ ┴┴─┘└─┘┴└─
3d-tiler(1.3.0) by Gaia3d, Inc.
JAVA Version : 17 (Oracle Corporation)

**Comment by znkim** [comment]
안녕하세요, @t2ols 

일반적으로 타일 피라미드를 형태로 생성하면서 데이터의 사이즈가 커지는 것은 정상입니다.
그러나 원본 데이터의 특성에 따라 해석이 달라질 수 있습니다. 
상세한 내용은 아래 데이터 특성이 파악되어야 자세히 답변 드릴 수 있을 것 같습니다.

 - 3D 파일의 개수
 - 텍스쳐의 사이즈가 큰 데이터
 - 텍스쳐 없이 메쉬 자체가 큰 데이터

감사합니다.

**Comment by t2ols** [comment]
답변 감사드립니다.
용량이 전체 용량이 아니고 타일 한개 용량이 400mb 가까이 되어서 질문 드립니다.

원본데이터 정보는 
    mesh : obj 1개 273mb
                Box dimensions 
                        X : 3690.69
                        Y : 3776.47
                        Z:134.234
                Faces : 1,845,445

    텍스처 이미지: 64개 png 531mb
    
입니다

**Comment by sdson** [comment]
안녕하세요, 

혹시, obj파일 받아서 분석할 수 있도록 샘플을 보내주실 수 있을까요?

**Comment by t2ols** [comment]
그건 어려울 것 같습니다. 그럼 일단 다른 데이터로 진행해 보겠습니다.

감사합니다.

**Comment by t2ols** [comment]
감사합니다 :)
