### ISSUE TITLE
테리언 파일에 따라 건물의 해발고를 설정할 수 있습니까?

### ISSUE THREAD

**Issue by IndigoCloud6** [Gaia3D/mago-3d-tiler#7]
테리언 파일에 따라 건물의 해발고를 설정할 수 있습니까?

**Comment by IndigoCloud6** [comment]
by terrain tiff file

**Comment by znkim** [comment]
네 그렇습니다. --terrain <geotiff path> 또는 -te <geotiff path> 옵션으로 건물의 해발 고도를 지정할 수 있습니다.
