### ISSUE TITLE
Facing issue in generating 3Dtiles (b3dm) from shapefile with height column

### ISSUE THREAD

**Issue by arjan-odedra** [Gaia3D/mago-3d-tiler#9]
Bug Description:
When generating 3D tiles (b3dm) using the following command:

**java -jar mago-3d-tiler-1.4.4-natives-linux.jar --input /home/santosh/Downloads/pcmc_ward13/pcmc_ward13_4326.shp --inputType shp -c 4326 -aa -ac B_Height_m --output /home/santosh/Downloads/pcmc_ward13/tiles/**

The 3D tiles are successfully generated; however, upon closer inspection, it appears that out of the six faces, three front faces are missing in most of the features. This issue is affecting the visual representation of the generated 3D tiles.

Steps to Reproduce:

Execute the provided command to generate 3D tiles.
Inspect the generated tiles, focusing on the front faces of the features.
Expected Result:
All six faces of the generated 3D tiles should be present, providing a complete and accurate representation of the features.

Actual Result:
In most cases, three front faces are missing, leading to an incomplete rendering of the features.

Additional Information:

mago-3d-tiler version: 1.4.4
Operating System: Ubuntu 20.4 

Please find attached images for your reference and zip file containing sample shapefile to be used with above command
[sample_data.zip](https://github.com/Gaia3D/mago-3d-tiler/files/14569776/sample_data.zip)
![Screenshot from 2024-03-12 11-56-49](https://github.com/Gaia3D/mago-3d-tiler/assets/130728642/3a961d55-a301-45c0-b151-f6a40c35b8a5)
![Screenshot from 2024-03-12 11-56-13](https://github.com/Gaia3D/mago-3d-tiler/assets/130728642/ca8369b8-f2b7-42aa-8ab0-21ca6b9407aa)
![Screenshot from 2024-03-12 11-56-02](https://github.com/Gaia3D/mago-3d-tiler/assets/130728642/6f2e84ac-6f1f-476a-8d37-ad86a1418cde)

**Comment by znkim** [comment]
Hello, @arjan-odedra

Looking at the picture, it looks like the triangles are reversed in orientation.
The "--altitude column" specifies the absolute height of the building floor, and the "--height column" specifies the absolute height of the building ceiling.
This is probably why the building-extrusion is upside down.

You can get closer to the desired result by using the -hc (--height column) option instead of the -ac (--altitude column) option.
```
java -jar mago-3d-tiler-1.4.4-natives-linux.jar --input /home/santosh/Downloads/pcmc_ward13/pcmc_ward13_4326.shp --inputType shp -c 4326 -aa -hc B_Height_m --output /home/santosh/Downloads/pcmc_ward13/tiles/
```

![image](https://github.com/Gaia3D/mago-3d-tiler/assets/87691347/6136b7d9-d8b7-4ae4-b508-2a18e91b9811)

**Comment by arjan-odedra** [comment]
Thanks @znkim for quick help it is working fine after regenerated tile using above command
` java -jar /home/arjan/Downloads/mago-3d-tiler-1.4.1-natives-linux.jar --input /home/arjan/Downloads/pcmc_b_ht_4326.shp --inputType shp -c 4326 -aa -hc B_Height_m --output ./`

![Screenshot from 2024-03-12 16-00-51](https://github.com/Gaia3D/mago-3d-tiler/assets/130728642/e69644a7-c747-4d0f-8a7f-013fbf4b9145)
![Screenshot from 2024-03-12 16-00-34](https://github.com/Gaia3D/mago-3d-tiler/assets/130728642/7546dcdf-58e8-4bc0-b29e-f63df4411c50)
